export const SUPABASE_URL = "https://aypihprprcohccewkjbj.supabase.co";
export const SUPABASE_KEY =
	"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5cGlocHJwcmNvaGNjZXdramJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTQyNTY1NTYsImV4cCI6MjAwOTgzMjU1Nn0.pJhkBLLkv3zoJSrvn5aTaOYPuVwgoxDy7kFgUR3Gh5M";
