/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function getConfiguration() {
    return invoke()<{ mode: Mode }>("get_configuration")
}

export function startSlideshow() {
    return invoke()<null>("start_slideshow")
}

export function installScreensaver() {
    return invoke()<null>("install_screensaver")
}

export type Mode = "SlideShow" | "ScreenSaver" | "Configuration"
